apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      name: chatapp-pod
      labels:
        app: chatapp
    spec:
      containers:
        - name: gopal1409-chatapp
          image: nginx
          ports:
           - containerPort: 8080
