apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-new
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nodestorage
  resources:
    requests:
      storage: 10Gi 
